### ISSUE TITLE
frontend-component-header (and footer) translation jobs are failing

### ISSUE THREAD

**Issue by robrap** [edx/frontend-component-header-edx#338] opened 2023-01-23 19:17 UTC
AC:
- [ ] Fix the failing jobs.
- [ ] Update the notification address to be Fed-BOM, rather than TNL (footer) and edx-platform (header).

See a sample failure here:
https://tools-edx-jenkins.edx.org/job/translations/job/frontend-component-footer-edx-push_translations/1150/console
```
17:46:35 npm run-script i18n_extract
17:46:36 
17:46:36 > @edx/frontend-component-footer-edx@1.0.0-semantically-released i18n_extract
17:46:36 > BABEL_ENV=i18n fedx-scripts babel src --quiet > /dev/null
17:46:36 
17:46:37 # Gathering JSON messages into one file...
17:46:37 ./node_modules/.bin/transifex-utils.js ./temp/babel-plugin-react-intl ./src/i18n/transifex_input.json
17:46:37 /edx/var/jenkins/jobs/translations/jobs/frontend-component-footer-edx-push_translations/workspace/ecommerce-scripts/frontend-component-footer-edx/node_modules/@edx/frontend-platform/i18n/scripts/transifex-utils.js:54
17:46:37   throw new Error('Found no messages');
17:46:37   ^
17:46:37 
17:46:37 Error: Found no messages
17:46:37     at Object.<anonymous> (/edx/var/jenkins/jobs/translations/jobs/frontend-component-footer-edx-push_translations/workspace/ecommerce-scripts/frontend-component-footer-edx/node_modules/@edx/frontend-platform/i18n/scripts/transifex-utils.js:54:9)
17:46:37     at Module._compile (node:internal/modules/cjs/loader:1105:14)
17:46:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
17:46:37     at Module.load (node:internal/modules/cjs/loader:981:32)
17:46:37     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
17:46:37     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
17:46:37     at node:internal/main/run_main_module:17:47
17:46:37 Makefile:31: recipe for target 'i18n.concat' failed
17:46:37 make: *** [i18n.concat] Error 1
17:46:39 Traceback (most recent call last):
17:46:39   File "transifex/push.py", line 82, in <module>
17:46:39     push(args.clone_url, args.repo_owner, merge_method=args.merge_method, skip_commit=args.skip_commit,
17:46:39   File "transifex/push.py", line 34, in push
17:46:39     repo.extract_translations()
17:46:39   File "/edx/var/jenkins/jobs/translations/jobs/frontend-component-footer-edx-push_translations/workspace/ecommerce-scripts/transifex/utils.py", line 218, in extract_translations
17:46:39     subprocess.run(['make', 'extract_translations'], check=True)
17:46:39   File "/usr/lib/python3.8/subprocess.py", line 516, in run
17:46:39     raise CalledProcessError(retcode, process.args,
17:46:39 subprocess.CalledProcessError: Command '['make', 'extract_translations']' returned non-zero exit status 2.
17:46:39 Build step 'Execute shell' marked build as failure
17:46:39 Archiving artifacts
17:46:44 Sending e-mails to: teaching-and-learning@2u-internal.opsgenie.net
17:46:45 Finished: FAILURE
```

**Comment by robrap** [comment] 2023-01-23 19:19
Adam suspects it could be related to https://github.com/openedx/frontend-build/pull/258

**Comment by BilalQamar95** [comment] 2023-01-24 10:39
I'm unable to access [jenkins console link](https://tools-edx-jenkins.edx.org/job/translations/job/frontend-component-footer-edx-push_translations/1150/console), however I did try this locally & failed to replicate the issue. Also I noticed that for `frontend-component-header-edx` the `frontend-build` version is pinned to v12.4.15 whereas the migration to formatjs update is in version [v12.4.16](https://github.com/openedx/frontend-build/compare/v12.4.15...v12.4.16)

cc: @abdullahwaheed

**Comment by brian-smith-tcril** [comment] 2023-01-24 15:21
> I'm unable to access [jenkins console link](https://tools-edx-jenkins.edx.org/job/translations/job/frontend-component-footer-edx-push_translations/1150/console), however I did try this locally & failed to replicate the issue. Also I noticed that for `frontend-component-header-edx` the `frontend-build` version is pinned to v12.4.15 whereas the migration to formatjs update is in version [v12.4.16](https://github.com/openedx/frontend-build/compare/v12.4.15...v12.4.16)
> 
> cc: @abdullahwaheed

it is definitely failing for https://github.com/openedx/frontend-component-header as of https://github.com/openedx/frontend-component-header/commit/b969522cd084ca06e878d00d14f4f9310e2b2d6f

the error log from jenkins also mentions https://github.com/edx/frontend-component-footer-edx, which was updated to 12.4.16 https://github.com/edx/frontend-component-footer-edx/commit/5b14d5c70f7a8d06cc0d695c3177188ba619287d

**Comment by robrap** [comment] 2023-01-24 15:30
@BilalQamar95: Here is the full Jenkins console details, while you are working out how to access Jenkins. See https://gist.github.com/robrap/f29b2b53000d8b6ccc180cc126c28c4e

**Comment by brian-smith-tcril** [comment] 2023-01-24 16:00
to add a bit more context, the failing line is
https://github.com/openedx/frontend-platform/blob/f90d4afb370f0856a399b972d0e3ae948e5e3eda/src/i18n/scripts/transifex-utils.js#L40, which is coming from

```js
const jsonDir = process.argv[2];
const messageObjects = gatherJson(jsonDir);

if (messageObjects.length === 0) {
  process.exitCode = 1;
  throw new Error('Found no messages');
}
```

when running `make extract_translations` locally on https://github.com/openedx/frontend-component-header/commit/664d05134b0a5341d949bdb4954738205258e91b, i can reproduce the error

when adding some extra console logs near the `const jsonDir = process.argv[2];`
```js
console.log(process.argv[2]);
const jsonDir = process.argv[2];
```
 i found `argv[2]` to be:
```
./temp/babel-plugin-react-intl
```

comparing this to https://github.com/openedx/frontend-component-header/commit/0cd8210ea79e9763d2960ec5b81cd7821f0a98eb, when adding the same logging i get the same output

so it seems `gatherJson` is expecting to find files in `./temp/babel-plugin-react-intl`, but is no longer finding anything
```js
function gatherJson(dir) {
  var ret = [];
  var files = glob.sync("".concat(dir, "/**/*.json"));
  files.forEach(function (filename) {
    var messages = JSON.parse(fs.readFileSync(filename));
    ret.push.apply(ret, _toConsumableArray(messages));
  });
  return ret;
}
```

**Comment by robrap** [comment] 2023-01-24 18:01
@connorhaugh noted that `frontend-app-account` is also failing.

**Comment by BilalQamar95** [comment] 2023-01-25 12:25
@robrap Thank you for the Jenkins console details. I was able to produce the issue and as @brian-smith-tcril identified, [frontend-build#258](https://github.com/openedx/frontend-build/pull/258) is in fact the cause for failing translations. We also noticed that last couple of [releases were failing](https://github.com/openedx/frontend-platform/actions/runs/3985364654) for frontend-platform which also included [ openedx/frontend-platform@ca06825](https://github.com/openedx/frontend-platform/commit/ca06825c7cc5f7b2ba6013a3e612fa3c17253f4f) updating frontend-build to `v12.4.16` which contains the `babel-plugin-formatjs` update.

I think our current issue is due to removal of extracted messages(`messagesDir`) since with `babel-plugin-formatjs`, the extracted messages are generated dynamically at runtime and they don't need to be written to disk. We can continue to use extracted messages by using `@formatjs/intl-compiler` package providing a way to extract translations from code and generate the corresponding messages files. However, with this approach we would be missing out on new features and performance benefits that come with `formatjs`. For now I have made a [revert for frontend-build#258](https://github.com/openedx/frontend-build/pull/296) while we explore this further. Apologies for inconvenience.

**Comment by robrap** [comment] 2023-01-25 13:11
@BilalQamar95: Thanks. Note the second AC regarding fixing the notifications. That should either be done as part of this ticket, or spun into a new ticket. Thank you.

**Comment by BilalQamar95** [comment] 2023-01-26 06:04
@robrap I made PRs in relevant mfes last night updating `frontend-build` version to `v12.4.19` containing the revert. My team is working on reviewing/merging them, once merged this will resolve the failing translation issues. I will also link this ticket on those PRs

**Comment by robrap** [comment] 2023-01-26 07:05
Thank you.

**Comment by BilalQamar95** [comment] 2023-03-10 06:54
Translation jobs failing issue has been addressed & resolved, this ticket can now be closed.

**Closed by BilalQamar95** 2023-03-10 06:54 UTC
